/**
 * B.S Evaluation — Serwist Service Worker
 * This file is compiled by @serwist/next separately.
 * It uses Service Worker APIs which are not available in the main tsconfig lib.
 */

import type { PrecacheEntry } from '@serwist/precaching';
import { precacheAndRoute, cleanupOutdatedCaches } from '@serwist/precaching';
import { CacheFirst, NetworkFirst, NetworkOnly } from '@serwist/strategies';

// @serwist/next requires the literal string "self.__SW_MANIFEST" in the source.
// TypeScript doesn't know about __SW_MANIFEST on the global self object,
// so we cast self to any to bypass the type check.
// eslint-disable-next-line @typescript-eslint/no-explicit-any
const sw = self as any;

// Precache all assets generated by @serwist/next
// IMPORTANT: Must use literal `self.__SW_MANIFEST` for @serwist/next to detect and inject.
// @ts-expect-error — __SW_MANIFEST is injected at build time by @serwist/next
precacheAndRoute(self.__SW_MANIFEST as (PrecacheEntry | string)[]);
cleanupOutdatedCaches();

// ═══════ استراتيجيات التخزين ═══════

sw.addEventListener('fetch', (event: any) => {
  const url = new URL(event.request.url);

  // API routes — always network (no caching for security)
  if (url.pathname.startsWith('/api/')) {
    event.respondWith(new NetworkOnly().handle({ event, request: event.request }));
    return;
  }

  // Static assets → Cache First
  const ext = url.pathname.split('.').pop() || '';
  if (['png', 'jpg', 'jpeg', 'webp', 'svg', 'gif', 'ico', 'woff2', 'woff', 'css', 'js'].includes(ext)) {
    event.respondWith(
      new CacheFirst({ cacheName: 'bs-static-v5' }).handle({ event, request: event.request })
    );
    return;
  }

  // HTML Pages → Network First with offline fallback
  if (event.request.mode === 'navigate' || event.request.destination === 'document') {
    event.respondWith(
      new NetworkFirst({
        cacheName: 'bs-pages-v5',
        networkTimeoutSeconds: 5,
      }).handle({ event, request: event.request }).catch(() => {
        return caches.match('/') || new Response(
          JSON.stringify({ error: 'لا يوجد اتصال بالإنترنت' }),
          { status: 503, headers: { 'Content-Type': 'application/json' } }
        );
      })
    );
    return;
  }

  // Fonts → Cache First
  if (url.pathname.includes('/fonts/')) {
    event.respondWith(
      new CacheFirst({ cacheName: 'bs-fonts-v5' }).handle({ event, request: event.request })
    );
    return;
  }
});

// Skip waiting on message
sw.addEventListener('message', (event: any) => {
  if (event.data?.type === 'SKIP_WAITING') {
    sw.skipWaiting();
  }
});

// Activate immediately
sw.addEventListener('activate', () => {
  sw.clients.claim();
});
